Dev
the-devid/ds-visualizer pull request #1
Opened 2024-04-11 15:32 UTC by the-devid

Сделана минимальная рабочая версия программы. В плнах добавить юнит-тесты на 2-3 Дерево и Observer, а также написать нормальное описание проекта и пояснения по дизайну.

2024-04-27 20:08 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Пиздец ты дружелюбный. Убрать все friend.

Убрать все mutable (я описал почему у тебя они возникли и как это фиксить).

Есть некоторые проблемы с обзервером. Я расписал подробно.

Еще очень плохой delay. Ты прав, что это максимально не безопасно. С таким подходом надо блокировать все источники сигналов в ядро, в частности весь пользовательский интерфейс. Но лучше сделать буффер для кадров анимации и посылать события по таймеру. Я расписал подробно.

Есть еще всякие разные мелочи. Но в целом у тебя какой-то спагетти код получается местами. Особенно проблема с уровнем доступа, когда ты пишешь obj1->obj2->obj3->...->objm Это прям плохо. Это говорит о том, что ты не продумал границы взаимодействия объектов. Я все отметил по коду, но не везде повторялся.

2024-04-27 20:08 UTC, DimaTrushin commented on CMakeLists.txt
> +  target_compile_options(ds_visualizer PRIVATE -fno-exceptions)
Я правильно понимаю, что ты отключил exception для clang и gcc, но не отключил для msvc? На самом деле есть две модели имплементации исключений и clang с gcc используют ту, где растет размер бинарника, но не падает производительность. А msvc использует второй стек и потому размер бинарника не растет, но ты платишь в run-time. Потому отключать исключения для clang и gcc почти не имеет смысла, а вот для msvc как раз наоборот.

2024-04-27 20:08 UTC, DimaTrushin commented on docs/2-3-tree.md
> +Реализация представлена шаблоном, зависящим от параметра `T` - типа данных, которые хранятся в дереве. Дерево, как множество вершин, хранится в виде набора узлов. Они представляются структурой `Node`
Небольшое замечание. Использование unique_ptr действительно облегчает работу с памятью. Но это не годится для очень больших структур данных. Потому что деструкторы будут вызваны каскадно один из другого и у тебя может закончиться стек. Кроме того, скорость такого исполнения будет так себе. Я так понимаю, что тут очень сильно спасет, что длина вызова на стеке не превосходит глубины дерева и вряд ли получится дерево в 1000 детей высотой.

2024-04-27 20:08 UTC, DimaTrushin commented on docs/2-3-tree.md
солидно

2024-04-27 20:08 UTC, DimaTrushin commented on main.cpp
> +    QApplication qt_app(argc, argv);
На самом деле это Qt runtime. Название этого класса обманывает. Задача этого класса обеспечить message driven экосистему в виде поддержки очереди сообщений и диспатча сигналов, а exec просто запускает event loop. Не знаю, зачем они так назвали эту штуку. И логика работы с Qt в том, что любой объект просто учится общаться в этой экосистеме и просто создается и ждет сообщений.

2024-04-27 20:08 UTC, DimaTrushin commented on main.cpp
> +    NVis::Application::Instance();
1) Отключи исключения на всех компиляторах, иначе плохо закончится на msvc.
2) Зачем ты сделал singleton? Что мешало создать объект на стеке? У тебя гарантируется, что все объекты в main существуют во время жизни программы. В Qt экосистеме все общение происходит с момента старта exec и до момента выхода из нее, то есть до завершения main. Потому все объекты, которые создаются в main видимы и адресуемы в течение всего времени работы приложения. Потому НЕТ никакого смысла делать singleton.

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.h
> +    ~Application();
Что мешало тут сделать default?

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.h
> +    static Application& Instance();
Ты нигде во всем коде не используешь глобальный доступ к этому ресурсу. Потому убери singleton и сделай обычный объект на стеке.

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.h
> +    Window window_;
Уже любопытно. Как так получилось, что view не живет внутри Window.

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.cpp
> +    model_.GetPort()->Subscribe(view_.GetPort());
Плохой дизайн. Когда ты пишешь  obj.subobj()->method() Это означает, что у объекта obj ты сделал не достаточный интерфейс, чтобы с ним взаимодействовать. Тебе вообще не надо иметь метод GetPort, тебе надо иметь метод subscribe. Кроме того, у порта как у абстрактного библиотечного класса метод называется subscribe. Но у model может быть много разных портов, потому чтобы их различать надо писать содержательные названия вроде subscribeToSomething и уже внутри этого метода вызывать subscribe у порта.
Аналогично у view, что это за getPort? Что за порт? Лучше дать нормальное название.

2024-04-27 20:08 UTC, DimaTrushin commented on src/window.h
> +    friend class Application;
Плохая тема. Убери эту дичь. Сделай нормальный интерфейс для взаимодействия с классом. Заведи в классе методы возвращающие указатель на нужные элементы. Не нарушай инкапсюляцию. Потому что теперь в любой точке Application может поменять все что угодно в классе window.

2024-04-27 20:08 UTC, DimaTrushin commented on src/window.h
> +    QPushButton* search_button_;
Приватные данные либо в самом начале в приватной зоне, либо в самом конце в приватной зоне. Никогда не складывай их в середине класса. Иначе просто невозможно найти данные, особенно если класс очень большой. Потому сначала помести статические константы и только потом помести приватные поля. И НИКОГДА НЕ пиши ничего после данных класса.

2024-04-27 20:08 UTC, DimaTrushin commented on src/window.h
> +    Window(QWidget* parent = nullptr);
Убери родителя. Ты все равно создаешь этот класс без него и у тебя Application будет менеджерить время жизни этого класса через автоматическую память.

2024-04-27 20:08 UTC, DimaTrushin commented on src/window.cpp
> +      layout_(new QGridLayout),
Когда создаешь Qt объекты, то делай одно из двух:
1) либо указывай им parent object, который будет ими владеть.
2) либо складывай его в unique_ptr через make_unique, и если потом ты хочешь передать его во владение другому Qt объекту, то делай это через release.
Иначе у тебя тут утечка памяти.

2024-04-27 20:08 UTC, DimaTrushin commented on src/window.cpp
> +    show();
Может быть стоит сделать вызов show в Application после того, как ты завершил свзь всех объектов?

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    friend class Application;
Какой ты дружелюбный. Убрать. У этих классов нет общего инварианта. Тут не должно быть возможности достучаться до внутренностей.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +
Не перемешивай в классе данные и методы. Невозможно проследить что именно лежит в классе, когда все вперемешку.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    Observer<TreeActionsBatch>* GetPort();
Дай нормальное название этому порту. Можешь даже убрать Get в названии. Типо ActionPort() или что-то в этом духе.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    std::vector<TreeActionsBatch> storage_;
Похорошему view должна быть stateless, ее задача только отрисовывать то, что ей прилетело. Любое сохранение каких-либо промежуточных данных обычно означает, что ты не выделил еще одну вспомогательную модель, которая должна была сделать некоторую дополнительную обработку данных, которую теперь за нее делает view.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    static constexpr int kDelayBetweenFrames = 300;
По хорошему такие вещи как delay и прочие параметры -- это часть ядра. View компонента может получить эту информацию из ядра, но хранить в ней эти параметры НЕ надо. Источник истинной информации всегда какая-то модель ядра. View всегда stateless и всегда только отрисовывает что-то. И она хранит лишь только то, что отвечает за отрисовку.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    //! Kind of pimpl.
почему kind of?

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    void HandleNotification(TreeActionsBatch actions);
Какого хрена тут этот метод делает в публичной зоне? Если этот метод вызывается на обработку сообщения из модели, то это приватный метод, который зовется из входного порта. Никто снаружи руками НЕ имеет права этот метод вызывать. Для всех View это черный ящик, который лишь дает возможность соединиться с портом. Ну и создать еще себя позволяет.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    ~View();
Все специальные методы вроде: дефолтный конструктор, копи конструктор, мув конструктор, копи присваивание, мув присваивание, любой другой конструктор и деструктор пиши рядом! Они обеспечивают семантику класса и не должны быть размазаны по всему классу между другими методами бизнес логики, которые уже делают содержательную работу.

2024-04-27 20:08 UTC, DimaTrushin commented on src/public.h
> +
Очень плохой файл. У тебя тут собрана куча не связанных никак forward declarations. Это все ухудшает локальность и читаемость кода. Кроме того, эта штука несет еще и include зависимость в виде std::vector. Нахуя это надо кроме увеличения времени компиляции из-за того, что ты в этом файле захочешь что-то поменять, не понятно.

2024-04-27 20:08 UTC, DimaTrushin commented on src/public.h
> +using TreeActionsBatch = std::vector<TreeAction>;
Если у тебя using является данным передаваемым по observable->observer соединению, то его надо вынести в отдельный h файл и это будет тот единственный h файл от которого будут зависить соединяемые объекты. Обычно такой файл содержит конечно не using, а структуру или класс с передаваемыми данными, но так будут понятны зависимости, а не так, что все скопом подключается хер пойми куда.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    void HandleNotification(TreeActionsBatch actions);
Ты принимаешь TreeActionsBatch по значению. А это std::vector. А это черевато копированием данных при каждом вызове, если ты забудешь поставить std::move(). Если ты хочешь гарантировать std::move, то лучше принимай по && ссылке. И вообще следи за тем, чтобы НИКОГДА НЕ копировать никакие контейнеры.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.h
> +    void AnimateQueries();
А ну вот и ясно что происходит. Ты на самом деле должен выделить дополнительную модель, которая принимает данные из исходной модели и потом создает по таймеру данные для анимации и уже эти данные улетают во view, которая их умеет отрисовывать. Тогда вся бизнес логика по анимации будет спрятана во второй модели, а не во view.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +View::~View() {}
1) Во-первых, View::~View() = default;
2) Во-вторых, порядок методов в cpp файле должен быть один в один такой же, как порядок методов в h файле!

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +    static constexpr qreal kCellWidth = 50;
Если тебе нужны какие-то константы для отрисовки, то их можно все завернуть в класс Palette (палитра). И более того, этот класс так же можно получать по observer-у из модели, которая отвечает за настройки палитры. И уже эту модель можно привязать к своим view и controller для управления палитрой. Но это нам сейчас не надо.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +    static constexpr qreal kCellWidth = 50;
Почему тип qreal?

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +    struct NodeForDraw {
Вот это выглядит как часть модели модели для отрисовки. Это должно быть НЕ во view.

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.cpp
> +        window_.key_edit_->clear();
Очень плохо. Ты соединяешь по сути не графический элемент с контроллером, а еще дополнительно хранишь какой-то глобальный контекст в рамках которого еще и управляешь отображением во view. Это противоречит самой сути view. View должна всегда быть в состоянии в котором находится модель. Я понимаю почему ты так сделал. В Qt к сожалению edit не является stateless view, он содержит в себе одновременно и данные текстового поля (то есть модель) и методы для отрисовки поля (view) и даже методы для изменения поля (то есть контроллер). Я думаю правильно сделать так. Сам контроллер должен внутри себя иметь ручки указывающие на управляемые объекты. И вся логика управления этими объектами должна быть спрятана в метод контроллера, которым ты управляешь. Просто будет так, что контроллер будет управлять сразу несколькими моделями (одна модель -- это дерево, а другая модель -- надпись в поле). По-хорошему надо еще разнести edit view и хранимые в нем данные, но это по дизайну Qt уже не так и нет в этом смысла. Потому надо работать с этой штукой как со сплавом модели, view и контроллера, предполагая, что ты обращаешься то к модели внутри edit, то к view внутри edit, то к контроллеру (хотя это никогда не должно быть нужно).

Еще плохо вот что. Обрати внимание что ты захватываешь контекст шире, чем тебе нужно. Ты хочешь по сути только перехватить key_edit_ а пеоехватываешь аж this, через который видишь window_ и только потом получаешь доступ к key_edit_. Это максимально плохо продуманные границы взаимодействия между объектами.

Очень плохая тема при соединении с методом делать содержательную работу. Возьми за привычку соединяться только с ГОТОВЫМ методом. Чтобы потом не надо было думать, а где же у тебя выполняется работа, которую ты найти не можешь. А она оказывается вполняется при соединении, просто все забыли, что она там и потому 100500 лет не могут отловить источник изменения данных.

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.cpp
> +    controller_.model_ = &model_;
Когда ты видишь код вида obj.value_ -- это УЖЕ кричит об ошибке дизайна. Дело в том, что ты ломаешь инкапсюляцию данных. Суффикс _ специально добавляется к приватным данным, чтобы их никто не сломал, а ты ломаешь приватные данные. Никогда не делай класс с публичными данными. Класс нужен для сохранения инвариантов, общайся с классом только через интерфейс.

Кроме того, у тебя кто-то мог позвать контроллер до этой строчки. А до этой строчки у тебя хранится в лучшем случае nullptr (если не мусорный адрес). И вообще говоря, кто-то мог позвать методы контроллера до этого момента. У тебя предусмотрена корректная работа контроллера в таком сценарии? Если нет, то надо передавать адрес на модель в конструкторе контроллера, потому что он часто не имеет смысла без модели. Он цепляется к ней насильно. Можно делать отключаеамые и трекаемые ручки на модель, я про это не рассказывал и не думаю, что этим надо заниматься сейчас.

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.cpp
> +    QObject::connect(window_.insert_button_, &QPushButton::clicked, &controller_, [this]() {
Имей в виду, что Qt соединения НЕ умеют оповещать при подписке. Потому их нельзя использовать для соединения модели и view, потому что иначе не гарантируется что при подписке view отражает состояние модели, что ломает всю идею observer паттерна. Тем не менее, для соединения элементов интерфейса с контроллером это рабочая схема, но учти замечание ниже.

2024-04-27 20:08 UTC, DimaTrushin commented on src/application.cpp
> +    window_.view_->setScene(&view_.scene_);
Это что за хуйня!???? Какого хуя у тебя view из window и view из application начинают шарить какой-то адрес!? Это ошибка дизайна, ты расчленил view на части и теперь у тебя часть франкенштейна лежит в window, а часть в application. Собери пожалуйста его обратно и убери это говно. У тебя только в контроллере сейчас разрешается иметь указатель на модель и все, никакие другие классы друг на друга не указывают (ибо это не безопасно вообще говоря). Даже в случае контроллера надо делать иначе, но пока это лишь в упрощение в угоду ускорения процесса.

2024-04-27 20:08 UTC, DimaTrushin commented on src/controller.h
> +    friend class Application;
Блять. Убрать убрать это говно к хуевой матери.

2024-04-27 20:08 UTC, DimaTrushin commented on src/controller.h
> +    Model* model_;
Елси я правильно понимаю, это все управляемые объекты. Передавай их в конструкторе контроллера или хотя бы сделай метод по их установке. И еще присвой им хотя бы nullptr тут, чтобы по дефолту в них мусор не писался, а то это черевато. Объект не должен быть в некорректном состоянии.

2024-04-27 20:08 UTC, DimaTrushin commented on src/controller.cpp
> +        Key key = input.toInt(&is_correct_value);
Обычно флаги особенно булевы означают проеб с дизайном. И в 99% случаев это отсутствие функции, которая должна была этот флаг установить через return. Тут же ты возвращаешь значение key. Я обычно в таких ситуациях делаю функцию
```cpp
std::optional<Key> try_convert_to_int(QString);
```
и просто проверяю, что optional не пуст. То есть ты по сути прячешь этот флаг внутрь optional.

2024-04-27 20:08 UTC, DimaTrushin commented on src/controller.cpp
> +            error_box.exec();
Вопрос, когда этот message box показывается основное окно программы не доступно? Потому что если доступно, то это может вызывать большие проблемы, так как по сути мы тут обрабатываем event loop в середине обработки другого сообщения в event loop. Это супер не безопасная техника.

2024-04-27 20:08 UTC, DimaTrushin commented on src/controller.cpp
> +    if (model_) {
Нарушение уровня абстракции. У тебя до и после этого if вызывается функция для управления кнопок, а для управления моделью ты пишешь тут конкретный код более низкого уровня абстракции. Я бы выделил этот код в отдельную функцию
```cpp
void handle_search_request(QString input) {
  if(!model_)
    return;
  ...
}
```
И так можно избавиться от лишнего nest-а внутри функции.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +    std::function<void()> on_unsubscribe_;
ОЧЕНЬ плохой дизайн. Ты хочешь получить данные и во время подписки и перед отпиской. Можно избавиться от получения данных при отписке, но при подписке ты должен получить корректное состояние модели, чтобы уметь отрисовать ее во view. Иначе это ломает всю идею MVC. Это ровно та же самая проблема, что есть в Qt connection. Когда ты соединяешь, ты не оповещаешь никого никакими данными, и потому там очень тяжело организовать нормальное MVC и когеррентность данных между ядром и GUI. Переделай. И на сколько я понимаю тебе все равно on_unsubscribe не нужно, можешь его убрать за ненадобностью.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +        observer->on_unsubscribe_();
Очень плохо. Максимально плохо, хуже некуда. Ты разрушил инвариант соединения, на который опирался observer и теперь зовешь метод оповещения. Сначала вызови on_unsubscribe и лишь потом рви соединение.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +        observer->SetObservable(nullptr);
Убрать. У тебя этот метод не должен поддерживать инвариант, он как раз для меж объектного взаимодействия. У тебя observer сам установит своего хозяина в nullptr.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +            Detach(subscribers_.front());
Здесь должно  быть subscribers_.front()->unsubscribe(); Иначе метод Detach не гарантирует всоблюдение инварианта (ты его руками насильно сделал и в итоге у тебя логика сломалась и часть действий задваивается.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +    void Notify(TData data) {
Плохой дизайн. Ты для оповещения требуешь явного знания данных, которыми ты оповещаешь. Это есть та причина, по которой ты не смог оповестить при подписке данными. Потому что твой observable НЕ знает этих данны, и все время ждет их снаружи. Это ничем не лучше чем Qt signals/slots. Вместо этого у тебя observable должна хранить доступ к источнику данных, который сообщается ему при создании. Например я храню std::function<const TData&()> data_. И когда надо получить к ним доступ делаю
```cpp
subscriber->on_notify_(data_());
```
Это позволяет оповещать с помощью данных всегда, но надо привязывать порт к данным в конструкторе.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +    std::function<void(TData)> on_notify_;
Тебя не сильно напрягает, что ты данные всегда by value передаешь? Просто если у тебя блокирующий observer данные можно передавать по const reference. Это будет дешевле и лучше в большинстве случаев.

2024-04-27 20:08 UTC, DimaTrushin commented on src/public.h
убрать это говно

2024-04-27 20:08 UTC, DimaTrushin commented on src/tree_action.h
> +    MemoryAddress node_address;
Из-за того что у тебя все разнесено по разным файлам, фиг уследишь что это за тип. Делай forward declaration явно там, где они нужны. Это повышает локальность и читаемость.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.h
> +    mutable Observable<TreeActionsBatch> port_;
Какого хуя? Нахуя тебе mutable порт?
UPD я нашел в observable ошибку, ты не сделал Notify метод const. Потому тебе нужны такие ябаные танцы с бубном. Исправь причину, а не используй кастыли для маскировки проблемы.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +    void Notify(TData data) {
Почему метод НЕ const? Судя по всему с этим связана проблема с тем, что у тебя mutable порт.

2024-04-27 20:08 UTC, DimaTrushin commented on src/observer.h
> +        for (auto& subscriber : subscribers_) {
Лишняя ссылка, у тебя хранятся указатели, потому нет смысла делать ссылку на указатель. Делай auto и все. Более того, это сделает указатель константным, но не сам observer, на который он ссылается. И у тебя все будет корректно работать.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.h
> +    //! Searches for the key `x` in 2-3 tree and returns erther it was found or not.
Это что какой-то синтаксис для системы автодокументации?

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.h
> +    Observable<TreeActionsBatch>* GetPort();
Дай нормальное название.
И еще у тебя слишком тяжелые данные передаются по копии по этому порту. Перепиши observer и observable так, чтобы данные всегда шли по константной ссылке. Для блокирующего обзервера это ок.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.h
> +    bool IsValid(Node* vertex);
какого хуя метод не константный?

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +    port_.Notify({TreeAction{.node_address = nullptr, .action_type = ENodeAction::StartQuery, .data = std::nullopt}});
Прелесть структур заключается в том, что ты можешь не указывать все поля, которые тебе не нужны. Сделай в структуре дефолтные значения для node_address = nullptr и для data = std::nullopt. Тогда ты тут можешь написать просто
```cpp
port_.Notify({TreeAction{.action_type = ENodeAction::StartQuery}});
```

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +    auto node_was_found = SearchByLowerBound(x);
Выглядит как нарушение уровня абстракции. У тебя тут делается сложное действие одной функцией. А потом идет низкоуровневая работа. Подумай, так ли это тут.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +             TreeAction{.node_address = root_.get(), .action_type = ENodeAction::MakeRoot, .data = std::nullopt}});
Вот это плохо. У тебя бизнес модель знает что-то про анимацию. Она сообщает что и как надо делать модели, которая будет создавать представление для отрисовки. Это плохо. Ты должен сообщить, что ты создаешь дерево, для этого ты посылаешь сигнал ENodeAction::Create, но дальше это уже геометрическая модель занимается вопросом, как именно этот Create анимировать. Это НЕ задача бизнес модели.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +    auto node_was_found = SearchByLowerBound(x);
Название как у булева флага. Если это объект, который найден, то node_found.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +    if (std::find(node_was_found->keys.begin(), node_was_found->keys.end(), x) != node_was_found->keys.end()) {
Опять кривое взаимодействие у тебя через два квалификатора доступа вызовы идут. Ты явно не продумал про взаимодействие объектов.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +    UpdateKeys(node_was_found);
Вот до жтого у тебя шел какой-то низкоуровневый код, а тут внезапно пошли вызовы высокоуровневых функций. Это ошибка дизайна. Плюс метод длиннющий.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +                port_.Notify(
Ты должен сообщать не действия, а состояние, по которому другая слушающая модель сама будет принимать решения о действиях.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +
Почему у тебя все такое спагетти образное. Прям даже не знаю как это читать.

2024-04-27 20:08 UTC, DimaTrushin commented on src/two_three_tree.cpp
> +bool TwoThreeTree::IsValid(Node* vertex) {
const или static

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +    void RecalculateLeafCountersRecursively(MemoryAddress vertex) {
пробел между функциями в cpp файле.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +    void RecalculateLeafCountersRecursively(MemoryAddress vertex) {
Ну неужели явное указание адреса нода не было бы более читаемым чем неизвестно где определенный псевдоним? Из названия вообще кажется, что это void*. А тогда какого хуя это vertex? И какого она типа? И где касты?

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +        // Cleaning backround colors for future.
Не надо комментировать код. Особенно если текст повторяет название функции, которая за ним следует. Я умею читать название функции. Компилятор понимает наличие функции. Ни я ни комплиятор не обратят внимание на назойливый комментарий.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +    void RecalculateLeafCounters() {
Я предпочитаю НЕ делать у структур методов. Я предпочитаю делать или статические или глобальные методы, которые принимают структуру.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +    loop.exec();
Если ты делаешь такую хуйню, то ты в обязательном порядке должен заблокировать весь пользовательский ввод. Потому что ты можешь делать delay где-то посередине вызова метода модели (потому что обзервер блокирующий), а значит если прилетит какой-то инпут от пользователя, то ты можешь зайти в метод модели посередине вызова другого метода и у тебя будет некорректный пиздец. Лучше делать НЕ так. Лучше создать модель для анимации, которая заполняет очередь данными для анимации и отправляет из этой очереди данные во view по таймеру. Так ты избавишься от плохого двойного обработчика сообщений. И не надо будет в наглую блокировать интерфейс для борьбы с некорректными состояниями. Это почти не возможно дебагать.

2024-04-27 20:08 UTC, DimaTrushin commented on src/view.cpp
> +        // It seems dangerous.
Это пиздец как опасно, максимально опасный опаснец. Я написал выше как это править. Иначе тебе надо на время этой функции полностью блокировать все элементы управления и все источники любых сигналов в ядро программы. Это очень тяжело сделать для больших проектов.

2024-05-15 19:42 UTC, the-devid commented on src/controller.cpp
> +            error_box.exec();
Да, недоступно:
> The user must click the OK button to dismiss the message box. The rest of the GUI is blocked until the message box is dismissed.

[Отсюда](https://doc.qt.io/qt-6/qmessagebox.html#the-property-based-api)

2024-05-16 14:14 UTC, the-devid commented on src/controller.cpp
> +    if (model_) {
Что-то какие-то трансцендентные размышления про уровни абстракции, чего-то я ещё не понимаю. Меня больше смутило сейчас, что там код повторяется по 3 раза. Вообще хочется видимо сделать какую-то функцию, которая принимает указатель на метод класса, и передавать туда соответственно что-то в духе `CallModelMethod(&Model::Insert)`, но выглядит как-то некрасиво. И если сделать неблокирующую анимацию, то смысла во всей этой функции как будто и не будет, потому что "высокоуровневый код" с включением кнопок уйдет. На момент написания _этого_ сообщения сделал эти `handle_..._request`.

2024-05-16 15:55 UTC, the-devid commented on src/observer.h
> +    void Notify(TData data) {
Потому что мне и в голову прийти не могло, что константный объект `A` может так функции позвать, что он сам в итоге поменяется, из-за того что "не меняться" в константном методе должно поле-указатель как адрес, а не как объект по нему. Очевидно конечно, почему так, но это ж надо заметить такой самородок коричневого цвета.

2024-05-16 17:54 UTC, the-devid commented on src/observer.h
> +    void Notify(TData data) {
Я вижу зачем при подписке оповещать данными (чтобы если модель уже в каком-то состоянии была - view это могла отрисовать; но такой сценарий банально не предполагался - модель же в самом начале к view подключается). Я вижу зачем для этого хранить `std::function` для получения данных. Я **не** понимаю зачем тот же трюк проворачивать для уведомления об изменении.

Вот конкретно: у меня есть дерево, хранит 100 элементов. Очевидно я не хочу на каждый кадр анимации копировать дерево целиком - дохрена как-то. Значит я хочу передавать изменения точечно и сейчас я это делаю именно так. Для того чтобы при подписке моделька отправила текущее состояние дерева видимо хочется сделать метод, который нагенерирует ~~полные штаны~~ вектор этих точечных изменений, и этот метод сохранить в Observable (и явно не хочется для этого действия заводить отдельную передачу через Observer копии - потребует слишком много действий ради константной экономии один раз за всю работу программы, а в реальности там всё равно сейчас ничего не передается).
А что обычные уведомления? У меня сейчас дерево просто когда вершину меняет зовет метод у Observable вида ```cpp
observable_.Notify_(данные про вершинку которая щас поменялась)
```
А как предлагается такие генерируемые буквально на лету по обстоятельствам данные прибивать к обзервабл? Не заводить же отдельное хранилище для изменений внутри модельки? Мы же всё равно будем эти данные создавать и тратить на это время и нам всё равно надо явно в конкретном месте кода их создать. Я бы предпочёл оставить тут Notify как есть, возможно только конст-ссылку или rvalue-ссылку (как где-то в другом месте предлагается) передавать.

2024-05-16 18:33 UTC, the-devid commented on src/two_three_tree.h
> +    //! Searches for the key `x` in 2-3 tree and returns erther it was found or not.
+ Да, есть такое
+ Ещё есть расширения которые комментарии с `//<tag>` друг от друга отличают. А я привык типа-документационные комментарии явно отделять от комментариев вида "пояснение почему сделано именно так". 
+ К пункту выше добавлю, что просто по факту хочется, чтобы комментарии-документация были уже хотя бы потому, что редактор/идешка высвечивают их при написании кода, что экономит время на "открыть документацию".

2024-05-16 18:38 UTC, the-devid commented on src/two_three_tree.h
> +    mutable Observable<TreeActionsBatch> port_;
Это мрак, кошмар и ужас, по моему мнению)
По факту поведение может поменяться при вызове константного `Contains(x)` (и это буквально написано в комментарии выше - что мешает обзёрверу после 10 нотифаев отписаться и больше модель никого не оповещает), чего вообще не ожидаешь. С mutable хотя бы был виден источник проблемы. Ну, сейчас проблемы не возникает, так что уберу.

2024-05-16 18:40 UTC, the-devid commented on src/two_three_tree.h
> +    bool IsValid(Node* vertex);
Хз, потому что забылось, а необходимости не возникало явной - константные методы не должны менять структуру данных **никак**, а значит в них и не нужно звать проверки на валидность. А это часть приватного интерфейса для дебаг-сборки же.

2024-05-16 18:48 UTC, the-devid commented on src/view.cpp
> +    static constexpr qreal kCellWidth = 50;
Потому что это некоторые параметры для объектов на плоскости. И потому что такой тип кушает QGraphicsScene (смею предположить, что второе вытекает из первого)

2024-05-16 19:08 UTC, the-devid commented on src/view.cpp
> +    struct NodeForDraw {
Мне что-то вообще не нравится, что "модель для отрисовки" и view это какие-то отделяемые понятия на уровне всего приложения _по отрисовке структуры данных_. Ну то есть у нас есть очевидная модель (структура данных), которые свои изменения шлёт "куда-то" и вот это "куда-то" вроде и должно же быть View. 
Тут по-хорошему наверное надо было назвать это и вправду как-нибудь вроде AnimationModel, а DrawingInfo назвать как-нибудь тоже по-модельски (GraphicsModel, GeometricModel, FrameModel) . Просто кроме штуки для анимации к view имеет отношение только QGraphicsView из пользовательского окошка, поэтому непонятно чего это так радикально нужно называть View-шкой только один виджет (!!!) из окна gui (а то и почему-то кнопки с полем ввода в придачу - пользователь это может и видит, но какое это имеет дело вообще к структуре данных и её визуализации??). Это как будто ломает всё понимание ради какой-то непонятной строгости.

2024-05-16 19:19 UTC, the-devid commented on src/view.cpp
> +    void RecalculateLeafCountersRecursively(MemoryAddress vertex) {
Надеюсь, я правильно понял, что его тут не хватает.

2024-05-16 19:29 UTC, the-devid commented on src/view.cpp
> +    void RecalculateLeafCountersRecursively(MemoryAddress vertex) {
Задумка такая: структура данных у нас это дерево, которое хранится в виде кучи узлов, к которым через указатели подвешены другие узлы. Хочется информацию об узлах передавать в эту рисуюущую модельку, чтобы оно хранило внутри себя данные для отрисовки (то есть информацию про каждый узел что там хранится, какие там дети, и какие-то ещё рисовательные данные). И вот чтобы отличать ноды друг от друга хочется им какие-то идентификаторы. И вот как-то ничего лучше не приходит в голову в качестве идентификаторов, чем явные адреса нод в памяти. Собственно, хочется работать с адресами просто как с числами.
А вот какого типа должны быть эти числа - в голову не пришло. Можно сказать, что `TwoThreeTree::Node*` но а) какого чёрта вообще приватный тип имеющий отношение только к кишкам дерева должен прорастать в представление и каким боком; б) тут просто по смыслу нужны только числа и зачем для этого, опять же, тянуть тип. В качестве кандидата был `intptr_t` или `uintptr_t`, но, если я правильно помню, проблема возникла в том, что это какие-то алиасы на что-то вроде `long int`, отчего нужно было вставить кучу кастов. А `void*` вроде как раз ничего кроме "какой-то адрес" и не значит, подходит чтобы его как число, по сути, передавать в мапы и хранить, а также не требует явных кастов. А псевдоним появился когда понадобилось переделать кучу `intptr_t` в `void*`. И вот щас зашла дискуссия о том, какой там тип использовать, и возможно мне придётся поменять `void*` на что-то другое. И сейчас мне для этого нужно будет один псевдоним поменять, а не по всему коду бегать.

2024-05-16 19:31 UTC, the-devid commented on src/view.cpp
> +        // Cleaning backround colors for future.
Вообще тут смысл комментария был не в первых трёх словах, а в следующих двух. Что вот мы отрисовали дерево на плоскости и вот именно сразу после этого чистим внутри структурки пометки о фоновых цветах *на будущее* (я не силён в английском, мб тут не for future должно быть а что-то подлиннее). Но дело не принципиальное, вроде и так понятно что происходит. Так что ок, удалю.

2024-05-16 19:39 UTC, the-devid commented on src/view.cpp
> +View::~View() {}
Кажется вторая проблема решается если перенести в .h 
Пока так и сделаю

2024-05-16 20:36 UTC, the-devid commented on src/view.cpp
> +    loop.exec();
Проблема скорее будет уже во внутрянке этой рисовалки, потому что сами анимации начинают крутиться только после выполнения всего запроса моделькой.
Сейчас по сути View это и есть модель для анимации, и она по таймеру плюёт информацию для отрисовки во внутреннюю структуру. Просто я хз почему, но почему-то я написал анимацию в продолжение блокирующего вызова обзёрвера, а можно было просто поставить таймер для какой-то функции, которая [плюёт очередной TreeActionsBatch графической модельке -> ставит таймер на вызов самой себя]. Видать забыл про гениальную структуру данных `std::queue`.

2024-05-16 20:37 UTC, the-devid commented on src/view.cpp
> +    loop.exec();
И тут наверное стоит сказать, что мне не нравится идея членить этот класс на отдельно модель для анимации и отдельно модель для рисования на плоскости. Во-первых, модель для анимации будет каким-то кастратом - это ж по сути будет просто очередь с таймером. Всё. Зато придётся добавлять обзёрвер-обзерваблы для просто лишнего перекладывания информации об изменениях. Кажется, что содержательного в этом классе будет вдвое меньше, чем работы по прокидыванию данных и "предоставления правильного инетфейса, чтобы obj.subobj()->subscribe() не было". И из-за блокирующего обзёрвера это будет по сути тот же вызов каких-то методов, просто обрезаны какие-то доступы до внутреннего хранилища геометрической модельки. Во-вторых, вообще кажется очень странным задумка расчленить анимацию на отдельно таймер и отдельно рисование кадра. Потому что от обратного кажется, что сделать класс, который по таймеру зовёт метод для отрисовки - проще для понимания, хотя бы. 
Ко всему это требует много какой-то бессодержательной рутины и рефакторинга, поэтому я это отложу на последнюю очередь и скорее уже в отдельной ветке.

2024-05-16 21:01 UTC, the-devid commented on src/view.h
> +    ~View();
Меня больше смущает что здесь есть деструктор, который ничего не делает. И никаких проблем с этой пятиметодной братией не возникает, копирующие автоматически убираются, а всё остальное само генерируется. Убрал его.

2024-05-16 21:13 UTC, the-devid commented on src/view.h
> +    void AnimateQueries();
Мне кажется для структуры данных, которую мы визуализируем, весь этот цирк с анимациями, рисованиями и виджетом в совокупности должен считаться view. Оттого этот класс так и называется. Собственно я проблему видел, может даже где-то в отчёте про это писал, но назвать эту плевалку данными по таймеру "отдельной моделью" ума не хватило. Содержательно где-то выше написал, что такое членение мне не по душе, но в отдельной ветке попробую сделать. В реальности будто бы можно решить все проблемы кроме "почему модель, которая какие-то геометрические фигуры рисует, живёт внутри модели для анимации?". И для этого вроде нужно просто сделать неблокирующую функцию для плевания данными + переделать этот DrawingInfo в pimpl-класс с ручкой по применению изменений.

2024-05-16 21:44 UTC, the-devid commented on src/view.h
> +    //! Kind of pimpl.
Ну обычно класс обёртка с интерфейсом, а по указателю некрасивая имплементация. Тут класс с содержательными вещами был, помимо некрасивой имплементации и методов-ручек.

2024-05-20 15:44 UTC, the-devid commented on src/application.cpp
> +    window_.view_->setScene(&view_.scene_);
Не понял проблему. Кроме контроллера и модели через указатели сейчас связываются все обзерваблы  c обзерверами в том числе (пока, правда, такая 1 пара). И QGraphicsScene + QGraphicsView, как я понял из документации, ведут себя как Model и View. В чём проблема, что у меня сейчас моделька, которая обходами в глубину обходит и рисует дерево на сцене, отделена от виджетов кутэшных? 
Видится, что франкенштейн будет как раз если я соберу в один класс логику с виджетами, и как их друг относительно друга располагать, с одной стороны и логику по рисованию прямоугольничков и отрезочков на плоскости с другой стороны. Да и зачем это, если, как я выше написал, они (сцена и виджет-view) и правда ведут себя как model и view?

2024-05-20 15:46 UTC, the-devid commented on src/application.h
> +    Window window_;
Потому что класс View у меня - это часть представления, которое генерирует анимацию и рисовашки на сцене. Зачем мне их объединять с GUI?

2024-05-20 15:53 UTC, the-devid commented on src/observer.h
> +    std::function<void()> on_unsubscribe_;
on_unsubscribe оставлю пожалуй, потому что выпиливать его из тестов будет геморройно

2024-05-20 16:07 UTC, the-devid commented on src/view.cpp
> +View::~View() {}
Видимо не решается - возникают беды с деструктором unique_ptr, если не перенести определение деструктора в .cpp

2024-05-20 16:18 UTC, the-devid commented on src/view.h
> +    std::vector<TreeActionsBatch> storage_;
Вот это "View" и есть эта модель, по задумке.

2024-05-21 12:25 UTC, the-devid commented on docs/2-3-tree.md
> +Реализация представлена шаблоном, зависящим от параметра `T` - типа данных, которые хранятся в дереве. Дерево, как множество вершин, хранится в виде набора узлов. Они представляются структурой `Node`
Да, тут строго логарифмическая высота и, соответственно, глубина рекурсии.

2024-05-21 12:37 UTC, the-devid commented on src/view.h
> +    static constexpr int kDelayBetweenFrames = 300;
Сейчас это часть модели для анимации. Вроде не View, вроде не какое-то отдельное "ядро". Нормально или нужно вынести в какой-нибудь class Core с кучей переменных, Palette и всем этим?

2024-05-21 12:40 UTC, the-devid commented on src/application.cpp
> +        window_.key_edit_->clear();
Вроде теперь Controller хранит указатель на QLineEdit и через него в отдельной функции что-то подтягивает/меняет.

2024-05-21 12:53 UTC, the-devid commented on src/two_three_tree.cpp
> +             TreeAction{.node_address = root_.get(), .action_type = ENodeAction::MakeRoot, .data = std::nullopt}});
Этот Create означает действие "Создался узел в дереве". Я вижу пока что проблемой может показаться то как именно группируются эти TreeAction в один батч. Но сейчас это разделение вроде было сделано по принципу "изменения объединяются в минимальный набор, чтобы дерево оставалось связным", что в общем было бы так же, как если бы мы просто отправляли View-шке полную копию всей модели (ведь мы бы не могли это делать, если бы дерево расчленилось и ещё не собралось до конца)

2024-05-21 12:54 UTC, the-devid commented on src/two_three_tree.cpp
> +    if (std::find(node_was_found->keys.begin(), node_was_found->keys.end(), x) != node_was_found->keys.end()) {
Что-то не догоняю вообще концепцию проблемы в этом месте

2024-05-21 12:58 UTC, the-devid commented on src/two_three_tree.cpp
> +    UpdateKeys(node_was_found);
Так оно всё на одном уровне делания каких-то действий с данными. Я бы мог оставить здесь не вызов функции, а "низкоуровневый код", но один и тот же код повторялся бы в 2 местах. Зачем? И что предлаегается вместо этого? Там же прямо просто меняются данные в паре мест, какие-то ассерты и уведомления через Observer.

2024-05-21 13:00 UTC, the-devid commented on src/two_three_tree.cpp
> +                port_.Notify(
Если дерево будет из 100 вершин, то предлагается все 100 вершин покопировать на каждое изменение чиселки в дереве? Я же не могу сохранить просто какой-то указатель или ссылку на дерево - дерево же потом поменяется.

2024-05-21 13:06 UTC, the-devid commented on src/two_three_tree.cpp
> +
Есть вершина, есть её дети, которых мы к ней только что подвесили. Им надо сказать кто теперь их родитель. Копию указателя `parent->children[i]` создать, чтобы к его полю обратиться? Тогда код будет в 2 раза длиннее и на каждое действие будет создаваться по переменной. Мне видится такой вариант хуже, другого не вижу - данные здесь один раз трогаются.

2024-05-21 13:20 UTC, the-devid commented
Из значительного не переделанного - модель уведомляет View об изменениях точечно, а не передает все данные. Это явно оптимальнее, но как я понял из комментариев надо было делать не так (но я не знаю как это сделать и оптимально, и нормально, и не умереть от реализации персистентной версии структуры данных в явном виде).
Ещё сейчас в дереве есть какие-то длинные строчки с доступом к данным, но как их сделать короче я не вижу.
Вообще все вопросы с реализацией модели (структуры данных) я увидел в последний момент, потому что на гитхабе у меня файл с реализацией 2-3 Дерева свернулся и я их до последнего не видел.

2024-09-15 17:47 UTC, merged